### ISSUE TITLE
无法run起来

### ISSUE THREAD

**Issue by fubd** [lulululbj/wanandroid#31]
报错信息如下：
2019-12-30 14:33:59.604 22417-22417/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: luyao.wanandroid, PID: 22417
    java.lang.RuntimeException: Unable to start activity ComponentInfo{luyao.wanandroid/luyao.wanandroid.ui.NavigationActivity}: android.view.InflateException: Binary XML file line #8 in luyao.wanandroid:layout/activity_navigation: Binary XML file line #8 in luyao.wanandroid:layout/activity_navigation: Error inflating class fragment
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)

@lulululbj @gdmec07120731

**Comment by fubd** [comment]
Caused by: android.view.InflateException: Binary XML file line #8 in luyao.wanandroid:layout/activity_navigation: Binary XML file line #8 in luyao.wanandroid:layout/activity_navigation: Error inflating class fragment
     Caused by: android.view.InflateException: Binary XML file line #8 in luyao.wanandroid:layout/activity_navigation: Error inflating class fragment
     Caused by: java.lang.RuntimeException: Exception inflating luyao.wanandroid:navigation/navigation line 61
        at androidx.navigation.NavInflater.inflate(NavInflater.java:90)
        at androidx.navigation.NavController.setGraph(NavController.java:425)
        at androidx.navigation.NavController.setGraph(NavController.java:407)
        at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.java:236)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2681)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:246)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1220)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1398)
        at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:109)
        at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:135)
        at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:356)
        at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:335)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1069)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at luyao.util.ktx.base.BaseActivity.onCreate(BaseActivity.kt:19)
        at luyao.wanandroid.ui.NavigationActivity.onCreate(NavigationActivity.kt:18)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
2019-12-30 14:33:59.605 22417-22417/? E/AndroidRuntime:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.UnsupportedOperationException: Cannot add action 2131230774 to androidx.navigation.ActivityNavigator$Destination@82cf373 as it does not support actions, indicating that it is a terminal destination in your navigation graph and will never trigger actions.
        at androidx.navigation.NavDestination.putAction(NavDestination.java:445)
        at androidx.navigation.NavInflater.inflateAction(NavInflater.java:321)
        at androidx.navigation.NavInflater.inflate(NavInflater.java:125)
        at androidx.navigation.NavInflater.inflate(NavInflater.java:132)
        at androidx.navigation.NavInflater.inflate(NavInflater.java:81)
        	... 38 more

**Comment by fubd** [comment]
![image](https://user-images.githubusercontent.com/29155847/71571965-ff8e9d00-2b17-11ea-812d-0c1accaa944f.png)

**Comment by AveryJones1** [comment]
应该ActivityNavigator.Destination里面重写的supportsActions()返回false导致的吧（可能这玩意不支持addAction？）把navigation.xml里的collectActivity下的action注掉就能跑了。具体原因还未深究，回头琢磨下，看作者的回复了

**Comment by lulululbj** [comment]
<activity> 标签下的确不支持 action ，希望以后会支持吧。
