### ISSUE TITLE
Failed resolution of: [Lkotlin/reflect/KProperty;

### ISSUE THREAD

**Issue by zzuliyikai** [lulululbj/wanandroid#47]
运行的时候一直报这个错，网上说是.aar的问题，但是您这没用到aar呀，还望前辈指教一下

**Comment by zzuliyikai** [comment]
这个是具体的报错信息   
Process: luyao.wanandroid, PID: 594
    java.lang.NoClassDefFoundError: Failed resolution of: [Lkotlin/reflect/KProperty;
        at luyao.wanandroid.App$Companion.<clinit>(App.kt)
        at luyao.wanandroid.App.<clinit>(App.kt)
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.Class.newInstance(Class.java:1572)
        at android.app.Instrumentation.newApplication(Instrumentation.java:999)
        at android.app.Instrumentation.newApplication(Instrumentation.java:984)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:569)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4767)
        at android.app.ActivityThread.access$1700(ActivityThread.java:169)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1495)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5581)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:968)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:763)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.reflect.KProperty" on path: DexPathList[[zip file "/data/app/luyao.wanandroid-1/base.apk"],nativeLibraryDirectories=[/data/app/luyao.wanandroid-1/lib/arm, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at luyao.wanandroid.App$Companion.<clinit>(App.kt) 
        at luyao.wanandroid.App.<clinit>(App.kt) 
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at java.lang.Class.newInstance(Class.java:1572) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:999) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:984) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:569) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4767) 
        at android.app.ActivityThread.access$1700(ActivityThread.java:169) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1495) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.app.ActivityThread.main(ActivityThread.java:5581) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:968) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:763) 
    	Suppressed: java.lang.ClassNotFoundException: kotlin.reflect.KProperty
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 18 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
